name: 'Inject Environment Variables for konfig test'
description: 'Injects vars from TEST_ENV into GITHUB_ENV and masks their values'
inputs:
  TEST_ENV:
    description: 'Environment variables to inject into GITHUB_ENV'
    required: true
runs:
  using: "composite"
  steps:
    - name: Mask secrets
      shell: bash
      run: |
        echo "${{ inputs.TEST_ENV }}" | while read -r line; do
          echo "::add-mask::${line#*=}"
        done

    - name: Set env vars for test
      shell: bash
      run: echo "${{ inputs.TEST_ENV }}" >> $GITHUB_ENV