name: Publish

on:
  workflow_call:
    inputs:
      konfig_yaml_dir:
        description: 'Path to directory which contains konfig.yaml'
        type: string
        required: true
        default: '.'

jobs:
  # Updates submodule SHAs if necessary and prepares for publishing
  pre-publish:
    runs-on: ubuntu-latest
    outputs:
      has_changesets: ${{ steps.detect-changesets.outputs.has_changesets }}
      sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Detect changeset files
        id: detect-changesets
        uses: konfig-dev/automation/.github/actions/private/detect-changesets@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Install konfig
        if: steps.detect-changesets.outputs.has_changesets == 'false'
        run: npm install -g konfig-cli

      - name: Detect SDK submodules
        if: steps.detect-changesets.outputs.has_changesets == 'false'
        id: sdk-submodules
        uses: konfig-dev/automation/.github/actions/private/detect-sdk-submodules@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Get version bump branch name
        id: branch-name
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        uses: konfig-dev/automation/.github/actions/private/get-branch-name@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Set git config
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        run: |
          git config --global user.email "publisher@konfigthis.com"
          git config --global user.name "konfig-publisher"

      - name: Merge submodule version bump PRs
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        env:
          KONFIG_API_KEY: ${{ secrets.KONFIG_API_KEY }}
        uses: konfig-dev/automation/.github/actions/private/merge-submodule-prs@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}
          sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
          head: ${{ steps.branch-name.outputs.branch_name }}
          base: ${{ github.ref_name }}

      - name: Update submodule references
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        uses: konfig-dev/automation/.github/actions/private/sync-submodules@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}
          sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
          submodules_base_branch: ${{ github.ref_name }}
          push_to: ${{ github.ref_name }}

  publish:
    runs-on: ubuntu-latest
    needs: pre-publish
    if: needs.pre-publish.outputs.has_changesets == 'false'
    container: # runs in docker container
      image: konfigdev/test-and-publish:staging
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PYPI_TOKEN_1: ${{ secrets.PYPI_TOKEN_1 }}
      PYPI_TOKEN_2: ${{ secrets.PYPI_TOKEN_2 }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Install konfig
        run: npm install -g konfig-cli

      - name: Setup test env vars
        uses: konfig-dev/automation/.github/actions/private/inject-testing-env-vars@main
        with:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig test

      - name: Set git config
        run: |
          git config --global user.email "publisher@konfigthis.com"
          git config --global user.name "konfig-publisher"
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          git config --global --add safe.directory /__w/$repo/$repo

      # If any SDKs are in submodules, then publishing might require pushing tags to the submodule repos
      - name: Set up SSH key for submodule access
        if: needs.pre-publish.outputs.sdk_submodule_dirs != ''
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SUBMODULE_DEPLOY_KEY_PYTHON }}
            ${{ secrets.SUBMODULE_DEPLOY_KEY_TYPESCRIPT }}
            ${{ secrets.SUBMODULE_DEPLOY_KEY_JAVA }}

      - name: Setup GPG for signing
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 -d | gpg --batch --passphrase "$GPG_PASSPHRASE" --import
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent
          gpg-connect-agent reloadagent /bye

      - name: Write settings.xml file for Java publishing
        uses: konfig-dev/automation/.github/actions/private/write-settings-xml@ENG-1483
        with:
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          ossrh_username: ${{ secrets.OSSRH_USERNAME }}
          ossrh_password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Publish SDKs
        run: konfig publish --all --skipTests --tolerateRepublish --skipRemoteCheck --ci
        working-directory: ${{ inputs.konfig_yaml_dir }}
        shell: bash