name: Regenerate SDKs

on:
  push:
    branches:
      - ENG-1187-test
  workflow_dispatch:
  workflow_call:
    inputs:
      konfig_yaml_dir:
        description: 'Path to directory which contains konfig.yaml'
        type: string
        required: true
        default: '.'

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:

      - name: Echo input
        run: echo ${{ inputs.konfig_yaml_dir }}
